### ISSUE TITLE
What's happening

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-usermeta#2]
All right, there are couple of things I've collected from "places" to do work on for this module: 

  - multiple keys GET
  - access levels (public, private, etc)
  - byte limit

Basically, this is just an interface for storing Key/Values in Redis, right? And it sounds like `meta` should not know about `directory` (because `users` will decide where to go, either here or there), am I correct?

**Comment by j3k0** [comment]
Yes, just an interface to store key/values associated with a user, with extra security options (different access privileges, byte limits).

It should only know about `authdb` and `usermeta` databases. Later on we will migrate from direct calls to `authdb`, to calls to `ganomede-directory`'s authentication endpoints.

**Comment by elmigranto** [comment]
I wonder if it would be easier to redo this from scratch (well, from boilerplate), coffee wierds me out now, but there are also a lot of non-related stuff, and useful code (`usermeta.coffee`) is basically redis `if (length <= 200) set/get` :)

**Comment by j3k0** [comment]
If you find you way around redoing from scratch, I think it'll be faster. But I'll let you decide.

You can also compile coffee to js and then work in js (`coffee -cb usermeta.coffee`) if you like.

**Comment by elmigranto** [comment]
Well there is just a single file that is actually used, I think, and it's pretty small. Everything else is either already in boilerplate repo, or not used (like bans stuff in user-api.coffee)

**Comment by j3k0** [comment]
Ok no problems. Can you make the new version a new branch in this repo (forked from root) ?

**Comment by j3k0** [comment]
just in case:
```
git checkout --orphan revamped
git reset --hard
```

**Comment by elmigranto** [comment]
Okay, I looked through everything, not sure which endpoints are left from `users`, and whether we need anything else:

`GET /:usernames/:keys`

fetch **public** keys

  - single or multiple users
  - single or multiple keys

example response

  - `get /joe/country` -> `"Russia"`
  - `get /joe,alice/country` -> `["Russia", "USA"]`
  - `get /joe,alice/country,displayName` -> `["Russia", "USA", "Joe", "A L I C E !"]` (which order do we want? :)

<hr/>

`GET /auth/:token/:keys`

fetch **public**, **protected** or **private** key(s)<br/>
(in case token is spoofed (secretMatches), allow fetching **internal** keys)

  - single user
  - single or multiple keys

<hr/>

`POST /auth/:token/:key`

write **public**, **protected** key<br/>
(in case token is spoofed (secretMatches), allow writing **private** and **internal** keys) 

Body is json with single {"value": "things…"}.

  - single user
  - single key

<hr/>

You mentioned creating endpoint specifically for *non-public* keys, not sure what you meant and why it requires own route. Is it because some **internal** keys are not bound to any specific user? Looks like we can do everything with just ones described above?

What we can not do with above design is set multiple keys at once. Perhaps we change it to be `POST /auth/:token` and accept `{"metaname": "value"}`? Or, if we already have client code, add new one, if that functionality is required.

Maybe it would make sense to return object instead of array when multiple keys / users are specified (or even all the time), so client code won't have to match requested array to returned one. Or maybe we always reply with format `{"username": {"metaname": "value"}` not depending on amount of staff requested.

Also, do we just omit non-accessible fields (say, we asked for **private** key from **public**-only endpoint).

**Comment by elmigranto** [comment]
If anything, I think always returning JSON with `user.meta: value` is preferable, because:

``` js
JSON.stringify([1, undefined, 2])
// "[1,null,2]"

JSON.stringify({joe: {country: 'Russia', protectedField: undefined}})
// '{"joe":{"country":"Russia"}}'
```

But I guess it all depends how client-code treats it, and whether we want to have `null`s as metadata values.

**Comment by elmigranto** [comment]
If it would be useful to client code, we can add `GET /:usernames/:keys?secret=API_SECRET` to fetch any number of field for any number of users.

**Comment by j3k0** [comment]
Sorry for the silence last 24h. `{"username": {"metaname": "value"}}` all over the place seems reasonable (also it solves the ordering problem)

> endpoint specifically for non-public keys

Because I didn't consider using spoofing to achieve that, which works as well.

**Comment by j3k0** [comment]
Just for some background (and pitching next tasks).

I have 2 use cases in mind for private metadata:

1. **mailchimp worker**. Can add a private metadata `{"mailchimp:registered": "true"}` to know quickly if a user is registered to the newsletter.
2. **rewarder worker**. Can add a private metadata `{"rewarder:apps": "wow,sudoku,lotr"}` to remember which apps the user is playing (when adding a new one to the list, it will send virtual currency reward to all existing apps)


... so, loading multiple keys for multiple users might not be necessary, so far.

**Comment by elmigranto** [comment]
Will we ever need non-user bound metadata? Looks like no, but to be sure…

**Comment by j3k0** [comment]
No, that's not what metadata are for. There's `ganomede-data` for global game data (which is only public so far, but we can extend if needed)

**Comment by elmigranto** [comment]
Do we need to be able to set multiple values in single call?

**Comment by elmigranto** [comment]
Good news! 🎉 🎉 🎉 

Pushed implementation of [this spec](https://github.com/j3k0/ganomede-usermeta/issues/2#issuecomment-283349696) (except with `Object` format) under `revamped` branch, not sure how to create PR. Let me know if everything looks fine, then I'll update docs and/or fix stuff accordingly, and we can switch/merge/what is appropriate term here :)

**Comment by j3k0** [comment]
Good job! 🥇👏👍 😄  Spec is alright.

Switched the code to master (required forced push, so you might have some warnings there).

Yes please update the README, they're so helpful!

There's one point I didn't discussed, mentioned, nor checked. Is storage format in DB still compatible with the existing metadata? (important!).

You can then proceed to emitting events from ganomede-users (next up on waffle).

**Comment by elmigranto** [comment]
> Is storage format in DB still compatible with the existing metadata? (important!).

Redis keys are `${username}:${key}` and values are JSON. Looks like coffee version just stores and returns strings; if that's the case then no and we have to change code or convert db.

**Comment by j3k0** [comment]
We don't want to convert the DB, has to be 100% compatible with data read and write by ganomede-users.

5dc2f73 allows `$` in key names (because `ganomede-users` uses keys starting with "$" in a few places, to store internal stuff). Like [friends](https://github.com/j3k0/ganomede-users/blob/feature/virtual-usermeta/src/friends-store.coffee#L17), etc...

**Comment by elmigranto** [comment]
Okay, so we only allow strings (meaning no `JSON.parse` / `JSON.stringify`) and keys can contain `$`?

**Comment by j3k0** [comment]
Yes, values always strings. Keys can contains "$" (I mentioned my naive commit in case you know where this has to be checked elsewhere in the code)

**Comment by elmigranto** [comment]
Well we only check env var itself on stratup, and refuse to read or write unknown keys, so no need to check elsewhere.

**Comment by elmigranto** [comment]
> You can then proceed to emitting events from ganomede-users (next up on waffle).

Okay.

On a sidenote, I don't think we see the same things in waffle — I have 0 user-related things there. Guess it has something to do with assigning stuff to me?..

![screenshot 2017-03-04 22 47 33](https://cloud.githubusercontent.com/assets/886388/23580911/9bb0db08-012c-11e7-87be-5d36de5d1539.png)

**Comment by j3k0** [comment]
did you allow access to private repos?

**Comment by j3k0** [comment]
(click "j3k0/ganomede" on top left, there's a "Add private repo" item -- or something)

**Comment by j3k0** [comment]
Next up:
<img width="326" alt="screen shot 2017-03-04 at 20 31 39" src="https://cloud.githubusercontent.com/assets/191881/23581280/a33ca36a-0119-11e7-97ac-e7090c75814a.png">

**Comment by j3k0** [comment]
Since we're in meta-discussion, a side request here as well. Can you try to limit your git commit titles to 72 chars (Git guidelines recommends 50, GitHub shows up to 72).

Commit titles should just give a general view of the change, full details fit in the commit description.

**Comment by j3k0** [comment]
maybe just put a empty line before bullet points, so they aren't included in the title.

<img width="701" alt="screen shot 2017-03-04 at 20 47 02" src="https://cloud.githubusercontent.com/assets/191881/23581463/03e31bb0-011d-11e7-9ce7-6a80b5b68f48.png">

**Comment by j3k0** [comment]
usermeta work seems 100% done?

**Comment by elmigranto** [comment]
> maybe just put a empty line before bullet points

Okay, no problem. (Though, github seems to accept single `\n` as title split; thought that was just SourceTree bug…)
<img width="293" alt="screenshot 2017-03-06 16 18 26" src="https://cloud.githubusercontent.com/assets/886388/23607896/93f2a862-0288-11e7-8fda-40ea3a4bcc0a.png">

> usermeta work seems 100% done?

It is.

**Comment by j3k0** [comment]
> github, SourceTree seems to accept single \n as title split;

Unfortunately I'm a command-line junky ;-) Command line `git` expects 2 `\n`.
