### ISSUE TITLE
Remove `USERMETA_INTERNAL_KEYS`

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-usermeta#4]
For reads/writes using `API_SECRET`, if the key isn't one of ("public", "protected", "private"), consider it as internal.

Remove the need for `USERMETA_INTERNAL_KEYS` configuration.

**reasoning**

Internal modules knowing the `API_SECRET` should be thrusted not to abuse the system. No need to add unnecessary complexity the configuration process.

**Comment by elmigranto** [comment]
merged #5 to `develop`.
