### ISSUE TITLE
Set multiple metadata at once

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-usermeta#7]
Adding multiple metadata at once can be useful, to prevent multiple requests like here: https://github.com/j3k0/ganomede-users/blob/63ebd503e6b7fa3512e562a192a59c6efa7ff8b5/src/users-api.coffee#L85-L92

**Comment by elmigranto** [comment]
Just added multi-write for single user, let me know if we need multiple `userId`s (like tracking friendships or smth).

**Comment by j3k0** [comment]
Great. Single-user should be enough.
