### ISSUE TITLE
`fakeredis`

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-usermeta#8]
I see you changed `redis` to `fakeredis`. May I ask why?
Tests are now 3 seconds instead of 200ms :(

I guess the reason is that it overwrites redis db in docker? Perphaps we change test DB to 16 or something (better yet, change production DB to non-default one).

**Comment by j3k0** [comment]
Because I generally don't run redis on my machine, then tests fail. `fakeredis` make tests context-independent.

You can include redis like this:

```js
redis = process.env.USE_REAL_REDIS
    ? require('redis')
    : require('fakeredis');
```

When you have a test redis instance define `USE_REAL_REDIS=1` to make tests run faster (don't make it the default behavior though).
